### ISSUE TITLE
Making '.tag' for each container

### ISSUE THREAD

**Issue by flyjwayur** [Rookies-RGSOC2016/Riot.js-Learning#3]
@gr2m @titay 
After the call, I'm trying to split the code to the separate tag files. 
I am getting this errors.
I checked all indentation and opening/closing html tags. I think I'm missing something.
'div' which has id 'control-group' seems to have syntaxError according to the indentation check. 
But I'm not sure what is incorrect as below code. :D

Error message in Console (/tags/create-app-container.tag.js:1 Uncaught SyntaxError: Unexpected token <)

``` js
     <form class="form-group" id="form-new-app">
          <h3 class="text-center">Let''s create Hoodie App :D</h3>
          <div class="control-group">
            <label class="control-label" for="empty-text">App Name</label>
            <input id="empty-text" type="text" class="form-control from-size" placeholder="Type your app name">
            </div>
            <div class="form-actions">
              <button id="cancel-create" type="button" class="btn btn_cancel pull-right btn-size-move">Cancel</button>
              <button id="choose-create" type="submit" class="btn btn-primary pull-right btn-size-move">create</button>
            </div>
          </form>
```

Error message in console (/tags/edit-app-container.tag.js:1 Uncaught SyntaxError: Unexpected token <)

``` js
  <form id="form-update-app">
    <p class="control-group">
      <label class="control-label" for="rename-app">New App Name:</label>
      <input class="form-control" id="rename-app" type="text" placeholder="Rename App here...">
      </p>
      <p>
        <button type="button" class="btn btn-default" id="cancelButton" >Cancel</button>
        <button type="submit" class="btn btn-primary" id="js-change-appname">Apply</button>
      </p>
    </form>
```

**Comment by flyjwayur** [comment]
@gr2m @titay
 I have other 2 errors in console. 'renderAppList' is in 'apps-container.tag file' and handleRoute is in 'app.tag' according to the context. I moved 'renderAppList' to app.tag to fix errors but those were not fixed. 

Error 1)
jQuery.Deferred exception: renderAppList is not defined ReferenceError: renderAppList is not defined
    at HTMLDocument.handleRoute (/tags/app.tag.js:17:7)
    at j (http://127.0.0.1:8080/vendor/jquery.min.js:2:29568)
    at k (http://127.0.0.1:8080/vendor/jquery.min.js:2:29882) undefined
Error 2)
jquery.min.js:2 Uncaught ReferenceError: renderAppList is not defined
